on:
  release:
    tags: ["v*.*.*"]
    types: [released]
name: Release
jobs:
  go-reference:
    runs-on: ubuntu-latest
    steps:
      - name: Update Go Reference
        run: |
          curl https://sum.golang.org/lookup/github.com/asger-noer/go-cursor@${{ github.ref_name }}
